name: "OpenAF's oJob action"
description: "Runs an OpenAF's oJob"
branding:
  icon : 'command'
  color: 'orange'
inputs:
  ojob:  
    description: 'The oJob to run'
    required: false
  def:
    description: 'The oJob definition in alternative to the ojob input'
    required: false
  oaf:
    description: 'A OpenAF script file to run'
    required: false
  script: 
    description: 'The OpenAF script contents to execute'
    required: false
  args:
    description: 'The oJob args to use'
    required: false
  dist:
    description: 'The OpenAF distribution to use'
    required: false
  pwd :
    description: 'Path to the working directory to use'
    required: false
runs:
  using: "composite"
  steps:
  # -------------------
  #- name: Setup Java 21
  #  uses: actions/setup-java@v4
  #  with:
  #    java-version: 21
  #    distribution: 'temurin'
  - shell: bash
    name : check runtime
    run  : |
      if [ ! -f /tmp/oaf/ojob ]; then
        CDIR=`pwd`
        mkdir /tmp/_oaf
        cd /tmp/_oaf
        curl https://openaf.io/getStatic.sh | DIST=${{ inputs.dist }} sh
        ./oaf -v
        cd /tmp
        bash -c "mv oaf* oaf"
        rm -rf /tmp/_oaf
        cd $CDIR
      fi
  - shell: bash
    name : Check for def
    if   : ${{ inputs.def }}
    run  : |
      echo ${{ format('''{0}''', inputs.def) }} > /tmp/temp.yaml
      if [ "${{ inputs.pwd }}" != "" ]; then
         cd ${{ inputs.pwd }}
      fi
      /tmp/oaf/ojob /tmp/temp.yaml ${{ inputs.args }}
  - shell: bash
    name : Check for oaf
    if   : ${{ inputs.oaf }}
    run  : |
      if [ "${{ inputs.pwd }}" != "" ]; then
         cd ${{ inputs.pwd }}
      fi
      /tmp/oaf/oaf -f ${{ inputs.oaf }} -e '${{ inputs.args }}'
  - shell: bash
    name : Check for script
    if   : ${{ inputs.script }}
    run  : |
      echo ${{ format('''{0}''', inputs.script) }} > /tmp/temp.js
      if [ "${{ inputs.pwd }}" != "" ]; then
         cd ${{ inputs.pwd }}
      fi
      /tmp/oaf/oaf -f /tmp/temp.js -e '${{ inputs.args }}'
  - shell: bash
    name : Check for ojob
    if   : ${{ inputs.ojob }}
    run  : |
      if [ "${{ inputs.pwd }}" != "" ]; then
         cd ${{ inputs.pwd }}
      fi
      /tmp/oaf/ojob ${{ inputs.ojob }} ${{ inputs.args }}
