name: Update version badge

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Update-Badge:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
    name       : Update badge oJob
    steps      :
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Update version badge
      uses: openaf/ojob-action@v3
      with:
        ojob: '.github/ojobs/updateVerBadge.yaml'
        dist: 't8'
        
    - name: Push
      env:
        GH_TOKEN: ${{ github.token }}
      uses: openaf/ojob-action@v3
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ badge" paths=.github/ojobs/version.svg'
        dist: 't8'
