name: Update version files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  Update-Files:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Update files oJob
    steps      :
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Update version files
      env :
        GH_TOKEN: ${{ github.token }}
      uses: openaf/ojob-action@v6
      with:
        ojob: '.github/ojobs/replaceVersion.yaml'
        dist: 't8'
        
    - name: Push
      env :
        GH_TOKEN: ${{ github.token }}
      uses: openaf/ojob-action@v6
      with:
        ojob: "ojob.io/git/hub/contentIn"
        args: "message=\"update files\" paths=README.md,USES.md branch=\"${{ github.ref_name }}\""
        dist: "t8"
